name: Badminton

services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: badminton-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - batminton_postgres_data:/var/lib/postgresql
    networks:
      - BadmintonNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5


networks:
  BadmintonNetwork:
    driver: bridge

volumes:
  batminton_postgres_data: