name: CI Checks

on:
  push:
    branches: [ main, test, Sukhatai ]
  pull_request:
    branches: [ main, test, Sukhatai ]

jobs:
  build-backend-docker:
    name: Test Build Backend Docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend 
          file: ./backend/Dockerfile 
          push: false
          tags: backend:test
          cache-from: type=gha 
          cache-to: type=gha,mode=max

  build-frontend-docker:
    name: Test Build Frontend Docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false 
          tags: frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

 
  